apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade,post-rollback
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    helm.sh/hook-weight: '5'
  labels:
    app.kubernetes.io/component: keycloak-config-cli
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/version: 24.0.5
    helm.sh/chart: keycloak-21.6.1
  name: keycloak-keycloak-config-cli
  namespace: keycloak
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: keycloak-config-cli
        app.kubernetes.io/instance: keycloak
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/version: 24.0.5
        helm.sh/chart: keycloak-21.6.1
    spec:
      automountServiceAccountToken: true
      containers:
      - command:
        - java
        - -jar
        - /opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar
        env:
        - name: KEYCLOAK_URL
          value: http://keycloak-headless:8080/
        - name: KEYCLOAK_USER
          value: user
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: keycloak-auth
        - name: IMPORT_FILES_LOCATIONS
          value: /config/*
        - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
          value: 'true'
        image: docker.io/bitnamilegacy/bitnami/keycloak-config-cli:5.12.0-debian-12-r6
        imagePullPolicy: IfNotPresent
        name: keycloak-config-cli
        resources:
          limits:
            cpu: 750m
            ephemeral-storage: 1024Mi
            memory: 768Mi
          requests:
            cpu: 500m
            ephemeral-storage: 50Mi
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
          seLinuxOptions: {}
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp
          name: empty-dir
          subPath: tmp-dir
        - mountPath: /config
          name: config-volume
      restartPolicy: Never
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      serviceAccountName: keycloak
      volumes:
      - emptyDir: {}
        name: empty-dir
      - configMap:
          name: keycloak-config-cli
        name: config-volume
  ttlSecondsAfterFinished: 600
